import { PurchaseProps } from "./Types";

export const ghostPurchases: PurchaseProps[] = [
  {
    purchasedAt: "Sep 30",
    purchasedById: "1",
    amount: (58.32).toFixed(2),
    isDeclined: false,
    isPending: true,
    userRatio: "50",
    partnerRatio: "50",
    description: "Fresh Mart",
    mccEmoji: "&#x1F951;",
    userShare: (58.32 * 0.5).toFixed(2),
    id: "100",
    isFake: true,
  },
  {
    purchasedAt: "Sep 29",
    purchasedById: "1",
    amount: (110.23).toFixed(2),
    isDeclined: false,
    isPending: false,
    userRatio: "60",
    partnerRatio: "40",
    description: "Power and Water",
    mccEmoji: "&#x26A1;&#xFE0F;",
    userShare: (110.23 * 0.6).toFixed(2),
    id: "101",
    isFake: true,
  },
  {
    purchasedAt: "Sep 28",
    purchasedById: "1",
    amount: (17.99).toFixed(2),
    isDeclined: false,
    isPending: false,
    userRatio: "50",
    partnerRatio: "50",
    description: "Netflix",
    mccEmoji: "&#x1F4FA;",
    userShare: (17.91 * 0.5).toFixed(2),
    id: "102",
    isFake: true,
  },
  {
    purchasedAt: "Sep 27",
    purchasedById: "1",
    amount: (67.75).toFixed(2),
    isDeclined: false,
    isPending: false,
    userRatio: "50",
    partnerRatio: "50",
    description: "Pet Express",
    mccEmoji: "&#x1F436;",
    userShare: (67.75 * 0.5).toFixed(2),
    id: "103",
    isFake: true,
  },
  {
    purchasedAt: "Sep 26",
    purchasedById: "1",
    amount: (51.61).toFixed(2),
    isDeclined: false,
    isPending: false,
    userRatio: "50",
    partnerRatio: "50",
    description: "DoorDash",
    mccEmoji: "&#x1F37D;",
    userShare: (51.61 * 0.5).toFixed(2),
    id: "104",
    isFake: true,
  },
  {
    purchasedAt: "Sep 25",
    purchasedById: "1",
    amount: (216.27).toFixed(2),
    isDeclined: false,
    isPending: false,
    userRatio: "50",
    partnerRatio: "50",
    description: "Best Buy",
    mccEmoji: "&#x1f3ae;",
    userShare: (216.27 * 0.5).toFixed(2),
    id: "105",
    isFake: true,
  },
];
