apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwolla-api
spec:
  selector:
    matchLabels:
      app: dwolla-api
  replicas: 2
  template:
    metadata:
      labels:
        app: dwolla-api
        affinityhash: "dwolla-api"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: affinityhash
                    operator: In
                    values:
                      - "dwolla-api"
              topologyKey: kubernetes.io/hostname
      serviceAccountName: dwolla-api
      volumes:
        - name: vault-token
          emptyDir:
            medium: Memory
      terminationGracePeriodSeconds: 90
      containers:
        - name: vault-agent-auth
          image: vault:1.2.3
          volumeMounts:
            - name: vault-token
              mountPath: /home/app/vault
          env:
            - name: VAULT_ADDR
              value: "https://vault.default.svc.cluster.local:8200"
            - name: ROLE
              value: "dwolla-api"
            - name: VAULT_SKIP_VERIFY
              value: "true"
          command:
            [
              "sh",
              "-c",
              "mkdir /etc/vault && echo -e \"exit_after_auth = false\npid_file = \\\"/home/vault/pidfile\\\"\n\nauto_auth {\n  method \\\"kubernetes\\\" {\n    mount_path = \\\"auth/kubernetes\\\"\n    config = {\n      role = \\\"$ROLE\\\"\n    }\n  }\n  sink \\\"file\\\" {\n    config = {\n      path = \\\"/home/app/vault/.vault-token\\\"\n    }\n  }\n}\n\" > /etc/vault/vault-agent-config.hcl && cat /etc/vault/vault-agent-config.hcl && vault agent -config=/etc/vault/vault-agent-config.hcl -log-level=debug",
            ]
          resources:
            requests:
              memory: "1Mi"
              cpu: "1m"
            limits:
              memory: "10Mi"
              cpu: "500m"
        - name: token-chmod
          image: busybox:1.31.0
          command:
            [
              "sh",
              "-c",
              "while true; do chmod 444 /home/app/vault/.vault-token; sleep 1; done && tail -f /dev/null",
            ]
          volumeMounts:
            - name: vault-token
              mountPath: /home/app/vault
          resources:
            requests:
              memory: "1Mi"
              cpu: "1m"
            limits:
              memory: "20Mi"
              cpu: "500m"
        - name: dwolla-api
          image: us-central1-docker.pkg.dev/infra-tgthr/tgthr-docker/api-dwolla:master
          command: ["/home/app/haskell-exe"]
          volumeMounts:
            - name: vault-token
              mountPath: /home/app/vault
          resources:
            requests:
              memory: "100Mi"
              cpu: "30m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
            - containerPort: 8443
          env:
            - name: PORT
              value: "4000"
            - name: VAULT_BASE
              value: "https://vault.default.svc.cluster.local:8200"
            - name: TOKEN_FILE_LOCATION
              value: "/home/app/vault/.vault-token"
            - name: "AMQP_BASE"
              value: "rhinelander-rabbitmq-ha.default.svc.cluster.local:5672"
            - name: "RMQ_ROLE"
              value: "generalrw-role"
          livenessProbe:
            httpGet:
              path: /ping
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              port: 4000
              path: /ping
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: dwolla-api-service
  labels:
    app: dwolla-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates an NEG after an Ingress is created
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
    # - port: 443
    #   protocol: TCP
    #   name: https
  selector:
    app: dwolla-api
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: dwolla-api-networkpolicy
# spec:
#   podSelector:
#     matchLabels:
#       app: dwolla-api
#   policyTypes:
#     - Ingress
#     - Egress
#   ingress:
#     - from:
#         - ipBlock:
#             cidr: 0.0.0.0/0
#       ports:
#         - protocol: TCP
#           port: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dwolla-api
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: apidwolla-web-internal
  labels:
    app: dwolla-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates an NEG after an Ingress is created
spec:
  ports:
    - targetPort: 8443
      port: 443
      protocol: TCP
  selector:
    app: dwolla-api
