apiVersion: v1
kind: Service
metadata:
  name: landing-page-service
  labels:
    app: landing-page
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates an NEG after an Ingress is created
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    # - port: 443
    #   protocol: TCP
    #   name: https
  selector:
    app: landing-page
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: landing-page
automountServiceAccountToken: true
