name: landing-page
version: 0.1.0.0
github: "paytgthr/monorepo"
license: AllRightsReserved
author: "Pay Tgthr, Inc"
maintainer: "hi@paytgthr.com"
copyright: "2019 Pay Tgthr, Inc"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - amqp
  - argon2
  - async
  - base64-bytestring
  - blaze-markup
  - blaze-html
  - bytestring
  - case-insensitive
  - clientsession
  - connection
  - cookie ==0.4.5
  - directory
  - ekg
  - ekg-core
  - exceptions
  - fast-logger
  - hashids
  - http2
  - http-api-data
  - http-client
  - http-client-tls
  - http-types
  - human-readable-duration
  - jwt
  - lifted-base
  - load-env
  - mtl
  - once
  - network
  - postgresql-simple
  - pretty-simple
  - QuasiText
  - random
  - raw-strings-qq
  - regex-tdfa
  - resource-pool
  - retry
  - scotty
  - scotty-cookie
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - stache
  - text
  - text-short
  - time
  - transformers
  - unix
  - unordered-containers
  - uuid
  - vault
  - vector
  - wai
  - wai-cors
  - wai-extra
  - wai-middleware-static
  - warp
  - warp-tls
  # Testing
  - hspec
  - hspec-wai
  - case-insensitive
  - regex-tdfa

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - ScopedTypeVariables
  - TupleSections
  - MultiWayIf
  - StrictData

library:
  source-dirs:
    - src
    - ../shared-haskell/lib

executables:
  landing-page-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - landing-page

tests:
  landing-page-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
    dependencies:
      - landing-page
