name: chewpaca
version: 0.1.0.0
github: "githubuser/chewpaca"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README

dependencies:
  - async
  - base >= 4.7 && < 5
  - aeson
  - aeson-pretty
  - amqp
  - base64-bytestring
  - blaze-html
  - blaze-markup
  - blaze-svg
  - bytestring
  - case-insensitive
  - cassava
  - clientsession
  - connection
  - cookie
  - cryptonite
  - ekg
  - ekg-core
  - exceptions
  - fast-logger
  - foreign-store
  - http2
  - http-client
  - http-client-tls
  - http-types
  - jwt
  - lifted-base
  - load-env
  - memory
  - mtl
  - once
  - postgresql-simple
  - pretty-simple
  - random
  - raw-strings-qq
  - regex-tdfa
  - resource-pool
  - retry
  - scotty
  - scotty-cookie
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - stache
  - text
  - text-short
  - time
  - transformers
  - unix
  - unordered-containers
  - uuid
  - vault
  - vector
  - wai
  - wai-cors
  - wai-extra
  - wai-middleware-static
  - warp
  - warp-tls

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - MultiWayIf
  - StrictData

library:
  source-dirs:
    - src
    - ../shared-haskell/lib
    - ../shared-haskell/db

executables:
  chewpaca-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chewpaca

tests:
  chewpaca-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chewpaca
