apiVersion: v1
kind: Service
metadata:
  name: apto-api-service
  labels:
    app: apto-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates an NEG after an Ingress is created
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
    # - port: 443
    #   protocol: TCP
    #   name: https
  selector:
    app: apto-api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apto-api
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: apiapto-web-internal
  labels:
    app: apto-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates an NEG after an Ingress is created
spec:
  ports:
    - targetPort: 8443
      port: 443
      protocol: TCP
  selector:
    app: apto-api
